#!/bin/sh
#
# $FreeBSD: 2017-09-12
#

# PROVIDE: aspf
# REQUIRE: LOGIN
# BEFORE: mail
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable clamd:
#
# aspf_enable="YES"
#
#

. /etc/rc.subr

name=aspf
rcvar=aspf_enable

# read settings, set default values
load_rc_config "$name"

: ${aspf_enable:=NO}

command=/Storage/System/ASPF/aspf.php
command_interpreter=/usr/bin/php
required_dirs=/Storage/System/ASPF
required_files=/Storage/System/ASPF/aspf.conf
start_cmd="$command -daemon"

start_precmd=
reload_cmd=
pidfile=/var/run/aspf.pid

run_rc_command "$1"
